apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: network-small-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
